/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Condition;
extern struct asn_TYPE_descriptor_s asn_DEF_SimpleSha256Condition;
extern struct asn_TYPE_descriptor_s asn_DEF_CompoundSha256Condition;
extern struct asn_TYPE_descriptor_s asn_DEF_ConditionTypes;
extern struct asn_TYPE_descriptor_s asn_DEF_Fulfillment;
extern struct asn_TYPE_descriptor_s asn_DEF_PreimageFulfillment;
extern struct asn_TYPE_descriptor_s asn_DEF_PrefixFulfillment;
extern struct asn_TYPE_descriptor_s asn_DEF_ThresholdFulfillment;
extern struct asn_TYPE_descriptor_s asn_DEF_RsaSha256Fulfillment;
extern struct asn_TYPE_descriptor_s asn_DEF_Ed25519Sha512Fulfillment;
extern struct asn_TYPE_descriptor_s asn_DEF_PrefixFingerprintContents;
extern struct asn_TYPE_descriptor_s asn_DEF_ThresholdFingerprintContents;
extern struct asn_TYPE_descriptor_s asn_DEF_RsaFingerprintContents;
extern struct asn_TYPE_descriptor_s asn_DEF_Ed25519FingerprintContents;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module Crypto-Conditions in CryptoConditions.asn */
	&asn_DEF_Condition,	
	&asn_DEF_SimpleSha256Condition,	
	&asn_DEF_CompoundSha256Condition,	
	&asn_DEF_ConditionTypes,	
	&asn_DEF_Fulfillment,	
	&asn_DEF_PreimageFulfillment,	
	&asn_DEF_PrefixFulfillment,	
	&asn_DEF_ThresholdFulfillment,	
	&asn_DEF_RsaSha256Fulfillment,	
	&asn_DEF_Ed25519Sha512Fulfillment,	
	&asn_DEF_PrefixFingerprintContents,	
	&asn_DEF_ThresholdFingerprintContents,	
	&asn_DEF_RsaFingerprintContents,	
	&asn_DEF_Ed25519FingerprintContents,	
	0
};

